workflows:
  ios-release:
    name: iOS Release (IPA)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

      # (Optionnel mais recommandé si tu configures le signing dans Codemagic)
      # ios_signing:
      #   distribution_type: ad_hoc   # ou app_store
      #   bundle_identifier: com.example.app

    scripts:
      - name: Flutter clean + pub get
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build IPA (release)
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
