workflows:
  ios-release:
    name: iOS Release (no codesign)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/archive/*.xcarchive
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
